<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcgvoom\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcgvoom/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUcgvoom.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUcgvoom\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUcgvoom\appProdProjectContainer([
    'container.build_hash' => 'Ucgvoom',
    'container.build_id' => '9624611f',
    'container.build_time' => 1587983211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcgvoom');
